# Generated by Django 5.1.7 on 2025-03-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
